### ISSUE TITLE
Schedulers are not deterministic

### ISSUE THREAD

**Issue by NinoScript** [mzaks/Colloop#1]
The test `testCoroutineWithMultipleCoRoutinesAndStepsOnDeidcatedQueue` will sometimes fail, the behavior you're testing is not guaranteed.

If you run the tests enough times, you will sometimes see this:
![screen shot 2017-05-18 at 10 57 03 am](https://cloud.githubusercontent.com/assets/589421/26208874/33ab79c4-3bb9-11e7-9e7f-c1a3f53f3352.png)

**Comment by mzaks** [comment]
Should be solved now by putting the `run` statements on the same queue
